// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
  //   variable: "--font-geist-mono",
  //   subsets: ["latin"],
  // });
  //  className={`${geistSans.variable} ${geistMono.variable} antialiased`}

  
export const metadata = {
  title: {
    template: "%s | Create Next",
    default: "Create Next",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <header style={{ background: "green"}}>Header</header> */}
        {children}
        {/* <footer style={{ background: "brown"}}>Footer</footer> */}
      </body>
    </html>
  );
}